version: '3.9'
services:
  app:
    container_name: django
    build:
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8000:8000
    env_file: ./docker/.env.dev
    command: poetry run python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: mysql
    image: mysql:8
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/conf.d:/etc/mysql/conf.d
    env_file: ./docker/.env.dev
    ports:
      - "3306:3306"
    privileged: true
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s