version: '3.9'
services:
  app:
    container_name: django
    build:
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8000:8000
    command: poetry run python manage.py runserver 0.0.0.0:8000